build-against-irida-master:
    script: make test IRIDA_VERSION=master
build-against-irida-development:
    script: make test IRIDA_VERSION=development
pep8:
    script: "scripts/verifyPEP8.sh"
#build:
#    script: make windows
#    artifacts:
#        paths:
#            - build/nsis/IRIDA_Uploader_*.exe
